// Business vertical configuration.
// cpc values are rough directional benchmarks (USD) used only to make the demo's
// budget math internally consistent — in production these should be pulled from
// Google Ads Keyword Planner / LinkedIn Campaign Manager forecasting APIs per market.
const VERTICALS = {
  // ---- B2C Local Service ----
  hvac_plumbing_electrical: {
    label: "HVAC / Plumbing / Electrical",
    group: "B2C Local Service",
    mode: "b2c",
    cpc: { google: 9.5, meta: 1.8, linkedin: null, print: null },
    weights: { income: 0.9, homeValue: 0.7, homeOwn: 1.0, age: 0.5 },
    defaultDealSize: 650,
    defaultCycleDays: 3,
  },
  landscaping_lawncare: {
    label: "Landscaping & Lawn Care",
    group: "B2C Local Service",
    mode: "b2c",
    cpc: { google: 6.5, meta: 1.4, linkedin: null, print: null },
    weights: { income: 1.0, homeValue: 0.9, homeOwn: 1.0, age: 0.6 },
    defaultDealSize: 1800,
    defaultCycleDays: 7,
  },
  roofing_exteriors: {
    label: "Roofing & Exteriors",
    group: "B2C Local Service",
    mode: "b2c",
    cpc: { google: 12.0, meta: 2.2, linkedin: null, print: null },
    weights: { income: 1.0, homeValue: 1.0, homeOwn: 1.0, age: 0.7 },
    defaultDealSize: 9500,
    defaultCycleDays: 21,
  },
  pest_control: {
    label: "Pest Control",
    group: "B2C Local Service",
    mode: "b2c",
    cpc: { google: 7.0, meta: 1.5, linkedin: null, print: null },
    weights: { income: 0.7, homeValue: 0.7, homeOwn: 0.9, age: 0.5 },
    defaultDealSize: 450,
    defaultCycleDays: 2,
  },
  cleaning_residential: {
    label: "Residential Cleaning Services",
    group: "B2C Local Service",
    mode: "b2c",
    cpc: { google: 5.5, meta: 1.3, linkedin: null, print: null },
    weights: { income: 1.0, homeValue: 0.6, homeOwn: 0.6, age: 0.4 },
    defaultDealSize: 180,
    defaultCycleDays: 2,
  },
  auto_repair_detailing: {
    label: "Auto Repair & Detailing",
    group: "B2C Local Service",
    mode: "b2c",
    cpc: { google: 4.5, meta: 1.2, linkedin: null, print: null },
    weights: { income: 0.6, homeValue: 0.3, homeOwn: 0.3, age: 0.4 },
    defaultDealSize: 320,
    defaultCycleDays: 1,
  },
  real_estate_agent: {
    label: "Real Estate Agent / Team",
    group: "B2C Local Service",
    mode: "b2c",
    cpc: { google: 3.5, meta: 1.6, linkedin: null, print: null },
    weights: { income: 1.0, homeValue: 1.0, homeOwn: 0.5, age: 0.6 },
    defaultDealSize: 8500,
    defaultCycleDays: 60,
  },
  dental_ortho: {
    label: "Dental / Orthodontics",
    group: "B2C Local Service",
    mode: "b2c",
    cpc: { google: 7.5, meta: 1.7, linkedin: null, print: null },
    weights: { income: 0.9, homeValue: 0.5, homeOwn: 0.5, age: 0.5 },
    defaultDealSize: 2200,
    defaultCycleDays: 14,
  },
  medspa_aesthetics: {
    label: "Med Spa / Aesthetics",
    group: "B2C Local Service",
    mode: "b2c",
    cpc: { google: 6.0, meta: 2.0, linkedin: null, print: null },
    weights: { income: 1.0, homeValue: 0.5, homeOwn: 0.3, age: 0.5 },
    defaultDealSize: 650,
    defaultCycleDays: 7,
  },
  fitness_studio: {
    label: "Fitness Studio / Gym",
    group: "B2C Local Service",
    mode: "b2c",
    cpc: { google: 3.0, meta: 1.3, linkedin: null, print: null },
    weights: { income: 0.6, homeValue: 0.3, homeOwn: 0.2, age: 0.3 },
    defaultDealSize: 900,
    defaultCycleDays: 10,
  },
  salon_spa: {
    label: "Salon & Spa",
    group: "B2C Local Service",
    mode: "b2c",
    cpc: { google: 2.8, meta: 1.2, linkedin: null, print: null },
    weights: { income: 0.7, homeValue: 0.4, homeOwn: 0.3, age: 0.3 },
    defaultDealSize: 150,
    defaultCycleDays: 3,
  },
  restaurant_local_food: {
    label: "Restaurant / Local Food",
    group: "B2C Local Service",
    mode: "b2c",
    cpc: { google: 2.0, meta: 1.1, linkedin: null, print: null },
    weights: { income: 0.5, homeValue: 0.3, homeOwn: 0.2, age: 0.2 },
    defaultDealSize: 55,
    defaultCycleDays: 1,
  },
  veterinary_clinic: {
    label: "Veterinary Clinic",
    group: "B2C Local Service",
    mode: "b2c",
    cpc: { google: 5.0, meta: 1.4, linkedin: null, print: null },
    weights: { income: 0.8, homeValue: 0.6, homeOwn: 0.6, age: 0.4 },
    defaultDealSize: 280,
    defaultCycleDays: 3,
  },
  childcare_tutoring: {
    label: "Child Care / Tutoring",
    group: "B2C Local Service",
    mode: "b2c",
    cpc: { google: 4.0, meta: 1.3, linkedin: null, print: null },
    weights: { income: 0.9, homeValue: 0.5, homeOwn: 0.5, age: 0.3 },
    defaultDealSize: 400,
    defaultCycleDays: 10,
  },
  moving_storage: {
    label: "Moving & Storage",
    group: "B2C Local Service",
    mode: "b2c",
    cpc: { google: 8.0, meta: 1.5, linkedin: null, print: null },
    weights: { income: 0.7, homeValue: 0.6, homeOwn: 0.4, age: 0.4 },
    defaultDealSize: 1100,
    defaultCycleDays: 14,
  },

  // ---- B2C High-Consideration / Big Ticket ----
  home_remodeling: {
    label: "Home Remodeling & Renovation",
    group: "B2C High-Consideration",
    mode: "b2c",
    cpc: { google: 14.0, meta: 2.4, linkedin: null, print: null },
    weights: { income: 1.0, homeValue: 1.0, homeOwn: 1.0, age: 0.7 },
    defaultDealSize: 22000,
    defaultCycleDays: 45,
  },
  solar_installation: {
    label: "Solar Installation",
    group: "B2C High-Consideration",
    mode: "b2c",
    cpc: { google: 16.0, meta: 3.0, linkedin: null, print: null },
    weights: { income: 1.0, homeValue: 0.9, homeOwn: 1.0, age: 0.6 },
    defaultDealSize: 24000,
    defaultCycleDays: 45,
  },
  custom_home_builder: {
    label: "Custom Home Builder",
    group: "B2C High-Consideration",
    mode: "b2c",
    cpc: { google: 13.0, meta: 2.2, linkedin: null, print: null },
    weights: { income: 1.0, homeValue: 1.0, homeOwn: 0.8, age: 0.6 },
    defaultDealSize: 85000,
    defaultCycleDays: 90,
  },
  wealth_management_local: {
    label: "Wealth Management / Financial Advisor",
    group: "B2C High-Consideration",
    mode: "b2c",
    cpc: { google: 18.0, meta: 2.6, linkedin: 9.0, print: null },
    weights: { income: 1.0, homeValue: 0.8, homeOwn: 0.7, age: 1.0 },
    defaultDealSize: 3500,
    defaultCycleDays: 60,
  },
  law_firm_local: {
    label: "Law Firm (Personal Injury / Family / Estate)",
    group: "B2C High-Consideration",
    mode: "b2c",
    cpc: { google: 22.0, meta: 2.8, linkedin: null, print: null },
    weights: { income: 0.7, homeValue: 0.5, homeOwn: 0.5, age: 0.7 },
    defaultDealSize: 4500,
    defaultCycleDays: 30,
  },

  // ---- B2B Professional Services ----
  equipment_rental_industrial: {
    label: "Equipment Rental / Industrial Supply",
    group: "B2B Professional Services",
    mode: "b2b",
    cpc: { google: 8.0, meta: null, linkedin: 7.5, print: null },
    weights: { companyDensity: 1.0, income: 0.4, homeValue: 0.2, homeOwn: 0.1 },
    defaultDealSize: 2800,
    defaultCycleDays: 21,
  },
  commercial_cleaning_janitorial: {
    label: "Commercial Cleaning / Janitorial",
    group: "B2B Professional Services",
    mode: "b2b",
    cpc: { google: 6.0, meta: null, linkedin: 6.0, print: null },
    weights: { companyDensity: 1.0, income: 0.3, homeValue: 0.1, homeOwn: 0.1 },
    defaultDealSize: 1800,
    defaultCycleDays: 30,
  },
  it_managed_services: {
    label: "IT Managed Services / MSP",
    group: "B2B Professional Services",
    mode: "b2b",
    cpc: { google: 12.0, meta: null, linkedin: 11.0, print: null },
    weights: { companyDensity: 1.0, income: 0.3, homeValue: 0.1, homeOwn: 0.1 },
    defaultDealSize: 3200,
    defaultCycleDays: 45,
  },
  accounting_bookkeeping: {
    label: "Accounting / Bookkeeping Firm",
    group: "B2B Professional Services",
    mode: "b2b",
    cpc: { google: 9.0, meta: null, linkedin: 8.5, print: null },
    weights: { companyDensity: 0.9, income: 0.5, homeValue: 0.2, homeOwn: 0.1 },
    defaultDealSize: 2400,
    defaultCycleDays: 30,
  },
  marketing_creative_agency: {
    label: "Marketing / Creative Agency",
    group: "B2B Professional Services",
    mode: "b2b",
    cpc: { google: 10.0, meta: null, linkedin: 10.5, print: null },
    weights: { companyDensity: 1.0, income: 0.4, homeValue: 0.1, homeOwn: 0.1 },
    defaultDealSize: 3800,
    defaultCycleDays: 30,
  },
  commercial_insurance_broker: {
    label: "Commercial Insurance Broker",
    group: "B2B Professional Services",
    mode: "b2b",
    cpc: { google: 11.0, meta: null, linkedin: 9.5, print: null },
    weights: { companyDensity: 1.0, income: 0.4, homeValue: 0.1, homeOwn: 0.1 },
    defaultDealSize: 3000,
    defaultCycleDays: 30,
  },
  staffing_recruiting: {
    label: "Staffing & Recruiting Agency",
    group: "B2B Professional Services",
    mode: "b2b",
    cpc: { google: 9.5, meta: null, linkedin: 12.0, print: null },
    weights: { companyDensity: 1.0, income: 0.3, homeValue: 0.1, homeOwn: 0.1 },
    defaultDealSize: 4500,
    defaultCycleDays: 21,
  },
  commercial_real_estate_pm: {
    label: "Commercial Real Estate / Property Management",
    group: "B2B Professional Services",
    mode: "b2b",
    cpc: { google: 10.5, meta: null, linkedin: 9.0, print: null },
    weights: { companyDensity: 0.9, income: 0.5, homeValue: 0.4, homeOwn: 0.2 },
    defaultDealSize: 6000,
    defaultCycleDays: 45,
  },
  waste_disposal_dumpster: {
    label: "Waste Disposal / Dumpster Rental",
    group: "B2B Professional Services",
    mode: "b2b",
    cpc: { google: 7.5, meta: null, linkedin: 6.5, print: null },
    weights: { companyDensity: 0.8, income: 0.3, homeValue: 0.3, homeOwn: 0.2 },
    defaultDealSize: 650,
    defaultCycleDays: 5,
  },
  business_consulting: {
    label: "Business Consulting",
    group: "B2B Professional Services",
    mode: "b2b",
    cpc: { google: 13.0, meta: null, linkedin: 13.5, print: null },
    weights: { companyDensity: 1.0, income: 0.4, homeValue: 0.1, homeOwn: 0.1 },
    defaultDealSize: 8500,
    defaultCycleDays: 45,
  },

  // ---- E-commerce / Retail ----
  ecommerce_dtc: {
    label: "E-commerce (DTC Retail)",
    group: "E-commerce / Retail",
    mode: "b2c",
    cpc: { google: 1.5, meta: 0.9, linkedin: null, print: null },
    weights: { income: 0.6, homeValue: 0.2, homeOwn: 0.1, age: 0.3 },
    defaultDealSize: 75,
    defaultCycleDays: 1,
  },
  local_retail_storefront: {
    label: "Local Retail Storefront",
    group: "E-commerce / Retail",
    mode: "b2c",
    cpc: { google: 2.2, meta: 1.0, linkedin: null, print: null },
    weights: { income: 0.6, homeValue: 0.3, homeOwn: 0.3, age: 0.3 },
    defaultDealSize: 60,
    defaultCycleDays: 1,
  },
};
